// utils/BangladeshDistricts.ts
export const districtsWithThanas = [
    {
      district: "Dhaka",
      thanas: ["Mirpur", "Uttara", "Gulshan", "Banani", "Mohammadpur", "Dhanmondi", "Ramna", "Tejgaon"],
    },
    {
      district: "Chittagong",
      thanas: ["Chandgaon", "Double Mooring", "Kotwali", "Pahartali", "Panchlaish", "Bakalia", "Patenga"],
    },
    {
      district: "Khulna",
      thanas: ["Khalishpur", "Sonadanga", "Daulatpur", "Khan Jahan Ali", "Aranghata"],
    },
    {
      district: "Rajshahi",
      thanas: ["Boalia", "Motihar", "Shah Makhdum", "Rajpara", "Chandrima"],
    },
    {
      district: "Sylhet",
      thanas: ["Jalalabad", "South Surma", "Osmani Nagar", "Kandigaon", "Shahporan"],
    },
    {
      district: "Barishal",
      thanas: ["Agailjhara", "Babuganj", "Bakerganj", "Banaripara", "Gaurnadi"],
    },
    {
      district: "Rangpur",
      thanas: ["Pirgachha", "Kaunia", "Badarganj", "Mithapukur", "Gangachara"],
    },
    {
      district: "Mymensingh",
      thanas: ["Trishal", "Gaffargaon", "Muktagachha", "Fulbaria", "Haluaghat"],
    },
    {
      district: "Comilla",
      thanas: ["Laksam", "Chauddagram", "Barura", "Brahmanpara", "Debidwar"],
    },
    {
      district: "Dinajpur",
      thanas: ["Birampur", "Birganj", "Biral", "Bochaganj", "Chirirbandar"],
    },
    {
      district: "Bogra",
      thanas: ["Adamdighi", "Dhunat", "Dhupchanchia", "Gabtali", "Kahaloo"],
    },
    { district: "Faridpur", thanas: ["Alfadanga", "Bhanga", "Boalmari", "Charbhadrasan"] },
    { district: "Tangail", thanas: ["Basail", "Bhuapur", "Delduar", "Ghatail"] },
    { district: "Jessore", thanas: ["Abhaynagar", "Bagherpara", "Chaugachha", "Jhikargachha"] },
    { district: "Pabna", thanas: ["Atgharia", "Bera", "Bhangura", "Chatmohar"] },
    { district: "Noakhali", thanas: ["Begumganj", "Chatkhil", "Companiganj", "Hatiya"] },
    { district: "Bhola", thanas: ["Borhanuddin", "Char Fasson", "Daulatkhan", "Lalmohan"] },
    { district: "Patuakhali", thanas: ["Bauphal", "Dashmina", "Galachipa", "Kalapara"] },
    { district: "Jhalokati", thanas: ["Kathalia", "Nalchity", "Rajapur"] },
    { district: "Barguna", thanas: ["Amtali", "Bamna", "Betagi", "Patharghata"] },
    { district: "Satkhira", thanas: ["Assasuni", "Debhata", "Kalaroa", "Shyamnagar"] },
    { district: "Meherpur", thanas: ["Gangni", "Mujibnagar"] },
    { district: "Narail", thanas: ["Kalia", "Lohagara"] },
    { district: "Chuadanga", thanas: ["Alamdanga", "Damurhuda", "Jibannagar"] },
    { district: "Kushtia", thanas: ["Bheramara", "Daulatpur", "Khoksa", "Mirpur"] },
    { district: "Magura", thanas: ["Mohammadpur", "Shalikha", "Sreepur"] },
    { district: "Sherpur", thanas: ["Jhenaigati", "Nakla", "Nalitabari", "Sreebardi"] },
    { district: "Natore", thanas: ["Bagatipara", "Gurudaspur", "Lalpur", "Singra"] },
    { district: "Chapainawabganj", thanas: ["Bholahat", "Gomastapur", "Nachole", "Shibganj"] },
    { district: "Gaibandha", thanas: ["Fulchhari", "Gobindaganj", "Palashbari", "Saghata"] },
    { district: "Nilphamari", thanas: ["Dimla", "Domar", "Jaldhaka", "Kishoreganj"] },
    { district: "Lalmonirhat", thanas: ["Aditmari", "Hatibandha", "Kaliganj", "Patgram"] },
    { district: "Thakurgaon", thanas: ["Baliadangi", "Haripur", "Pirganj", "Ranisankail"] },
    { district: "Habiganj", thanas: ["Ajmiriganj", "Bahubal", "Baniyachong", "Lakhai"] },
    { district: "Sunamganj", thanas: ["Derai", "Dharampasha", "Dowarabazar", "Jagannathpur"] },
    { district: "Netrokona", thanas: ["Atpara", "Barhatta", "Khaliajuri", "Madan"] },
    { district: "Kishoreganj", thanas: ["Austagram", "Bajitpur", "Hossainpur", "Itna"] },
    { district: "Manikganj", thanas: ["Daulatpur", "Ghior", "Harirampur", "Saturia"] },
    { district: "Munshiganj", thanas: ["Gazaria", "Lohajang", "Sreenagar", "Tongibari"] },
    { district: "Narsingdi", thanas: ["Belabo", "Monohardi", "Palash", "Raipura"] },
    { district: "Gopalganj", thanas: ["Kashiani", "Kotalipara", "Muksudpur", "Tungipara"] },
    { district: "Shariatpur", thanas: ["Bhedarganj", "Damudya", "Gosairhat", "Naria"] },
    { district: "Madaripur", thanas: ["Kalkini", "Rajoir", "Shibchar"] },
    { district: "Rajbari", thanas: ["Baliakandi", "Goalandaghat", "Pangsha"] },
    { district: "Panchagarh", thanas: ["Atwari", "Boda", "Debiganj", "Tetulia"] },
    { district: "Kurigram", thanas: ["Bhurungamari", "Char Rajibpur", "Chilmari", "Rajarhat"] },
    { district: "Jamalpur", thanas: ["Baksiganj", "Dewanganj", "Islampur", "Madarganj"] },
    { district: "Cox's Bazar", thanas: ["Chakaria", "Kutubdia", "Moheshkhali", "Teknaf"] },
    { district: "Bandarban", thanas: ["Alikadam", "Lama", "Naikhongchhari", "Rowangchhari"] },
    { district: "Khagrachhari", thanas: ["Dighinala", "Lakshmichhari", "Mahalchhari", "Panchhari"] },
    { district: "Rangamati", thanas: ["Bagaichhari", "Barkal", "Kaptai", "Langadu"] },
    { district: "Feni", thanas: ["Chhagalnaiya", "Daganbhuiyan", "Parshuram", "Sonagazi"] },
    { district: "Lakshmipur", thanas: ["Kamalnagar", "Raipur", "Ramganj", "Ramgati"] },
    { district: "Chandpur", thanas: ["Faridganj", "Haimchar", "Kachua", "Matlab Uttar"] },
    { district: "Bagerhat", thanas: ["Chitalmari", "Fakirhat", "Mongla", "Rampal"] },
    { district: "Jhenaidah", thanas: ["Harinakunda", "Kaliganj", "Kotchandpur", "Shailkupa"] },
    { district: "Narayanganj", thanas: ["Araihazar", "Bandar", "Rupganj", "Sonargaon"] },
    { district: "Gazipur", thanas: ["Kaliakair", "Kaliganj", "Kapasia", "Sreepur"] },
    { district: "Joypurhat", thanas: ["Akkelpur", "Kalai", "Khetlal", "Panchbibi"] },
    { district: "Naogaon", thanas: ["Atrai", "Badalgachhi", "Dhamoirhat", "Porsha"] },
    { district: "Pirojpur", thanas: ["Bhandaria", "Kawkhali", "Mathbaria", "Nazirpur"] },
    { district: "Brahmanbaria", thanas: ["Ashuganj", "Bancharampur", "Kasba", "Nabinagar"] }
  ];